import { useEffect, useMemo, useState } from 'react'
import { BarChart3, Bell, ChevronDown, CircleDollarSign, CreditCard, FileText, LayoutDashboard, Menu, Plus, ReceiptIndianRupee, Search, Settings, Users, WalletCards, X, ArrowRight, Sparkles, LogOut, CheckCircle2, UserPlus, SlidersHorizontal, Eye, EyeOff, ShieldCheck, Trash2 } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { api } from './services/api'

const money = n => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n||0))
const initials = name => name?.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()
const nav = [['overview','Overview',LayoutDashboard],['expenses','Expenses',ReceiptIndianRupee],['balances','Balances',WalletCards],['members','Members',Users],['settlements','Settlements',CreditCard],['reports','Reports',BarChart3]]
const colors = ['#176b58','#b48b4e','#447f91','#bd6f5e','#557d67','#c8a561']

function App(){
  const [session,setSession]=useState(null),[authChecking,setAuthChecking]=useState(true),[loginError,setLoginError]=useState('')
  const [backLogoutPrompt,setBackLogoutPrompt]=useState(false)
  const [groups,setGroups]=useState([]),[groupId,setGroupId]=useState(1),[view,setView]=useState('overview')
  const [dashboard,setDashboard]=useState(null),[members,setMembers]=useState([]),[expenses,setExpenses]=useState([])
  const [balances,setBalances]=useState([]),[settlements,setSettlements]=useState([]),[users,setUsers]=useState([])
  const [loading,setLoading]=useState(true),[error,setError]=useState(''),[toast,setToast]=useState('')
  const [modal,setModal]=useState(''),[mobile,setMobile]=useState(false),[query,setQuery]=useState(''),[profile,setProfile]=useState(false)
  const databaseAuthError=/access denied.*using password:\s*no|er_access_denied_error/i.test(error)

  const signOut=async()=>{await api.logout().catch(()=>{});setBackLogoutPrompt(false);setSession(null);setDashboard(null);setGroups([]);setMembers([]);setExpenses([]);setBalances([]);setSettlements([]);setError('');setProfile(false)}
  const signIn=async(username,password)=>{setLoginError('');try{const nextSession=await api.login({username,password});setSession(nextSession)}catch(e){setLoginError(e.message)}}

  const load=async id=>{
    setLoading(true); setError('')
    try{
      const [d,m,e,b,s]=await Promise.all([api.dashboard(id),api.members(id),api.expenses(id),api.balances(id),api.settlements(id)])
      setDashboard(d);setMembers(m);setExpenses(e);setBalances(b);setSettlements(s)
    }catch(e){setError(e.message)}
    finally{setLoading(false)}
  }
  useEffect(()=>{api.session().then(setSession).catch(()=>{}).finally(()=>setAuthChecking(false))},[])
  useEffect(()=>{if(!session)return;api.groups().then(setGroups).catch(e=>setError(e.message));api.users().then(setUsers).catch(()=>{});},[session])
  useEffect(()=>{if(session&&groupId)load(groupId)},[session,groupId])
  useEffect(()=>{
    if(!session)return
    const preserveWorkspace=()=>window.history.pushState({splitFlowSession:true},'',window.location.href)
    const onBack=()=>{preserveWorkspace();setBackLogoutPrompt(true)}
    preserveWorkspace()
    window.addEventListener('popstate',onBack)
    return()=>window.removeEventListener('popstate',onBack)
  },[session])
  useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),2800);return()=>clearTimeout(t)}},[toast])

  const filteredExpenses=useMemo(()=>expenses.filter(e=>`${e.description} ${e.category} ${e.payer}`.toLowerCase().includes(query.toLowerCase())),[expenses,query])
  const spent=Number(dashboard?.summary?.spent||0),budget=Number(dashboard?.group?.budget||0),remaining=budget-spent
  const categoryData=dashboard?.categories?.map(x=>({name:x.category,value:Number(x.value)}))||[]
  const navClick=v=>{setView(v);setMobile(false)}
  const refresh=()=>load(groupId)
  const after=msg=>{setModal('');setToast(msg);refresh();api.groups().then(setGroups)}

  if(authChecking) return <div className="loading-screen"><div className="loader-ring"/><b>Securing your workspace…</b></div>
  if(!session)return <LoginPage onLogin={signIn} error={loginError}/>
  if(loading&&!dashboard) return <div className="loading-screen"><div className="loader-ring"/><b>Loading your workspace…</b><span>Connecting to the expense service</span></div>

  return <div className="app-shell">
    <aside className={`sidebar ${mobile?'open':''}`}>
      <div className="brand"><div className="brand-logo"><CircleDollarSign size={22}/></div><div><b>SplitFlow</b><span>Expense workspace</span></div><button className="close-side" onClick={()=>setMobile(false)}><X/></button></div>
      <div className="group-switcher"><span>ACTIVE GROUP</span><button onClick={()=>setModal('group')}><div className="group-icon">{dashboard?.group?.name?.slice(0,1)}</div><div><b>{dashboard?.group?.name||'Campus Crew'}</b><small>{members.length} members</small></div><ChevronDown size={16}/></button></div>
      <nav>
        <label>WORKSPACE</label>{nav.map(([key,label,Icon])=><button key={key} className={view===key?'active':''} onClick={()=>navClick(key)}><Icon size={18}/><span>{label}</span>{key==='expenses'&&<em>{expenses.length}</em>}</button>)}
        <label className="nav-bottom">ACCOUNT</label><button onClick={()=>setToast('Settings are ready for the next project phase.')}><Settings size={18}/><span>Settings</span></button>
      </nav>
      <div className="sidebar-user"><div className="avatar">{initials(session.username)}</div><div><b>{session.username}</b><small>Group admin</small></div><button onClick={()=>setProfile(!profile)}><MoreDots/></button></div>
    </aside>
    <main className="main">
      <header className="topbar">
        <button className="menu" onClick={()=>setMobile(true)}><Menu/></button>
        <div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search expenses, categories, people…"/>{query&&<button onClick={()=>setQuery('')}><X size={15}/></button>}</div>
        <div className="top-actions"><span className={`status-dot ${error?'bad':''}`}><i/>{error?'Offline':'Live'}</span><button className="icon-btn"><Bell size={18}/><b>3</b></button><div className="profile-wrap"><button className="profile" onClick={()=>setProfile(!profile)}><div className="avatar">{initials(session.username)}</div><span><b>{session.username}</b><small>Administrator</small></span><ChevronDown size={15}/></button>{profile&&<div className="profile-menu"><button onClick={()=>setToast('Profile panel opened.')}><Users size={16}/>Profile</button><button onClick={()=>setToast('Settings panel opened.')}><Settings size={16}/>Settings</button><hr/><button onClick={signOut}><LogOut size={16}/>Log out</button></div>}</div></div>
      </header>
      <div className="content">
        {error&&<div className={`error-banner ${databaseAuthError?'database-error':''}`}><div><b>{databaseAuthError?'MySQL password is missing or incorrect':'Backend connection failed'}</b><span>{databaseAuthError?'The backend reached MySQL as root without a password. Set DB_PASSWORD in backend/.env to your MySQL password, then restart the backend.':error}</span>{databaseAuthError&&<small>Copy backend/.env.example to backend/.env, replace YOUR_MYSQL_PASSWORD, and run npm run dev again from the backend folder.</small>}</div><button onClick={refresh}>Retry</button></div>}
        <section className="page-head"><div><span className="eyebrow"><Sparkles size={14}/> SHARED FINANCE</span><h1>{view==='overview'?'Good morning, Laxman':nav.find(x=>x[0]===view)?.[1]}</h1><p>{view==='overview'?'Here’s the financial snapshot for your group today.':'Manage your shared expenses, balances and settlements in one place.'}</p></div><button className="primary" onClick={()=>setModal('expense')}><Plus size={18}/>Add expense</button></section>

        {view==='overview'&&<Overview dashboard={dashboard} balances={balances} expenses={expenses} categoryData={categoryData} spent={spent} budget={budget} remaining={remaining} money={money} setView={setView}/>}
        {view==='expenses'&&<Expenses expenses={filteredExpenses} money={money} onAdd={()=>setModal('expense')}/>}
        {view==='balances'&&<Balances balances={balances} money={money}/>}
        {view==='members'&&<Members groupId={groupId} members={members} users={users} onAdd={()=>setModal('member')} onDone={()=>after('Member removed from group')}/>}
        {view==='settlements'&&<Settlements groupId={groupId} settlements={settlements} balances={balances} money={money} onAdd={()=>setModal('settlement')} onDone={()=>after('Payment recorded')}/>}
        {view==='reports'&&<Reports categoryData={categoryData} spent={spent} budget={budget} expenses={expenses} money={money}/>}
      </div>
    </main>
    {modal==='expense'&&<ExpenseModal groupId={groupId} members={members} onClose={()=>setModal('')} onDone={()=>after('Expense added successfully')}/>}
    {modal==='member'&&<MemberModal groupId={groupId} users={users} existingMembers={members} onClose={()=>setModal('')} onDone={()=>{api.users().then(setUsers).catch(()=>{});after('Member added to group')}}/>}
    {modal==='settlement'&&<SettlementModal groupId={groupId} balances={balances} onClose={()=>setModal('')} onDone={()=>after('Settlement recorded')}/>}
    {modal==='group'&&<GroupModal groups={groups} groupId={groupId} setGroupId={setGroupId} onClose={()=>setModal('')} onDone={g=>{setGroups(g);setModal('')}}/>}
    {backLogoutPrompt&&<Modal title="Log out?" description="Are you sure you want to log out before going back?" onClose={()=>setBackLogoutPrompt(false)}><div className="modal-actions logout-actions"><button type="button" className="secondary" onClick={()=>setBackLogoutPrompt(false)}>No, stay signed in</button><button type="button" className="primary" onClick={()=>void signOut()}>Yes, log out</button></div></Modal>}
    {toast&&<div className="toast"><CheckCircle2 size={18}/>{toast}</div>}
  </div>
}

function LoginPage({onLogin,error}){const [username,setUsername]=useState('Laxman'),[password,setPassword]=useState(''),[visible,setVisible]=useState(false),[submitting,setSubmitting]=useState(false);const submit=async event=>{event.preventDefault();setSubmitting(true);await onLogin(username,password);setSubmitting(false)};return <main className="auth-page"><section className="auth-showcase"><div className="auth-brand"><span className="auth-brand-mark"><CircleDollarSign size={23}/></span><span><b>SplitFlow</b><small>Expense workspace</small></span></div><div className="auth-copy"><span className="eyebrow"><Sparkles size={14}/> SHARED FINANCE</span><h1>Good plans.<br/><em>Clear balances.</em></h1><p>SplitFlow</p></div><div className="auth-graphic" aria-hidden="true"><div className="auth-graphic-line line-one"/><div className="auth-graphic-line line-two"/><div className="auth-graphic-bars"><i/><i/><i/><i/><i/><i/><i/><i/><i/></div><div className="auth-graphic-axis"/></div><div className="auth-showcase-foot"><span>PRIVATE GROUP WORKSPACE</span><span>01 / FINANCE</span></div></section><section className="auth-panel"><form className="auth-form" onSubmit={submit}><span className="auth-kicker"><ShieldCheck size={16}/> SECURE SIGN IN</span><h2>Welcome back</h2><p className="auth-subtitle">Sign in to your SplitFlow workspace.</p><label>Username<input autoComplete="username" autoCapitalize="none" required value={username} onChange={event=>setUsername(event.target.value)} placeholder="Your username"/></label><label>Password<span className="auth-password"><input autoComplete="current-password" required type={visible?'text':'password'} value={password} onChange={event=>setPassword(event.target.value)} placeholder="Enter your password"/><button type="button" aria-label={visible?'Hide password':'Show password'} onClick={()=>setVisible(!visible)}>{visible?<EyeOff size={17}/>:<Eye size={17}/>}</button></span></label>{error&&<div className="auth-error" role="alert">{error}</div>}<button className="primary auth-submit" disabled={submitting}>{submitting?'Signing in…':'Sign in'}<ArrowRight size={17}/></button><div className="auth-secure-note"><ShieldCheck size={14}/>Your session is private to this browser.</div></form><div className="auth-panel-foot">SPLITFLOW <span>·</span> GROUP FINANCE</div></section></main>}

const MoreDots=()=> <span className="more-dots">•••</span>

function Overview({dashboard,balances,expenses,categoryData,spent,budget,remaining,money,setView}){
 const pct=budget?Math.min(100,spent/budget*100):0
 return <div className="stack">
  <div className="stats">
   <Stat icon={WalletCards} label="Total spent" value={money(spent)} detail={`${dashboard?.summary?.expense_count||0} recorded expenses`} tone="violet"/>
   <Stat icon={CircleDollarSign} label="Group budget" value={money(budget)} detail={`${Math.max(0,100-pct).toFixed(0)}% budget remaining`} tone="blue"/>
   <Stat icon={ArrowRight} label="You receive" value={money(Math.max(0,balances.find(x=>x.name==='Laxman Reddy')?.balance||0))} detail="Current net balance" tone="green"/>
   <Stat icon={Users} label="Members" value={balances.length} detail="Active in this group" tone="amber"/>
  </div>
  <div className="grid-two">
   <section className="panel budget-card"><header><div><h2>Budget overview</h2><p>Spending against the monthly group limit</p></div><button className="ghost" onClick={()=>setView('reports')}>Details <ArrowRight size={15}/></button></header><div className="budget-line"><strong>{money(spent)}</strong><span>of {money(budget)}</span></div><div className="progress"><i style={{width:`${pct}%`}}/></div><div className="budget-foot"><span><i className="legend-dot spent"/>Spent <b>{pct.toFixed(0)}%</b></span><span className={remaining<0?'danger-text':''}>{remaining>=0?`${money(remaining)} remaining`:`${money(Math.abs(remaining))} over budget`}</span></div></section>
   <section className="panel balance-card"><header><div><h2>Who owes whom</h2><p>Net position in this group</p></div><button className="ghost" onClick={()=>setView('balances')}>View all <ArrowRight size={15}/></button></header><div className="balance-list">{balances.slice(0,4).map(b=><div key={b.user_id}><div className="person"><span className="avatar small">{initials(b.name)}</span><span><b>{b.name}</b><small>Paid {money(b.paid)}</small></span></div><strong className={b.balance>=0?'positive':'negative'}>{b.balance>=0?'+':''}{money(b.balance)}</strong></div>)}</div></section>
  </div>
  <div className="grid-wide">
   <section className="panel"><header><div><h2>Spending by category</h2><p>Where the group money is going</p></div><button className="icon-square"><SlidersHorizontal size={17}/></button></header><div className="chart-wrap"><ResponsiveContainer width="100%" height={245}><BarChart data={categoryData}><CartesianGrid vertical={false} stroke="#edf0f5"/><XAxis dataKey="name" axisLine={false} tickLine={false} fontSize={12}/><YAxis axisLine={false} tickLine={false} fontSize={11}/><Tooltip formatter={v=>money(v)}/><Bar dataKey="value" radius={[7,7,0,0]}>{categoryData.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Bar></BarChart></ResponsiveContainer></div></section>
   <section className="panel recent"><header><div><h2>Recent expenses</h2><p>Latest activity in the group</p></div><button className="ghost" onClick={()=>setView('expenses')}>View all <ArrowRight size={15}/></button></header><div className="recent-list">{expenses.slice(0,5).map(e=><div key={e.expense_id}><span className="expense-icon">{e.category?.slice(0,1)}</span><span className="expense-main"><b>{e.description}</b><small>{e.payer} · {e.category}</small></span><strong>{money(e.amount)}</strong></div>)}</div></section>
  </div>
 </div>
}

function Stat({icon:Icon,label,value,detail,tone}){return <div className="stat"><span className={`stat-icon ${tone}`}><Icon size={19}/></span><div><small>{label}</small><strong>{value}</strong><em>{detail}</em></div></div>}

function Expenses({expenses,money,onAdd}){return <div className="panel table-panel"><header><div><h2>Expense ledger</h2><p>Every shared transaction, payer and category.</p></div><button className="primary small" onClick={onAdd}><Plus size={16}/>New expense</button></header><div className="table-scroll"><table><thead><tr><th>Expense</th><th>Payer</th><th>Category</th><th>Split</th><th>People</th><th>Amount</th></tr></thead><tbody>{expenses.map(e=><tr key={e.expense_id}><td><b>{e.description}</b><small>{new Date(e.expense_date).toLocaleDateString('en-IN')}</small></td><td><span className="person-inline"><span className="avatar tiny">{initials(e.payer)}</span>{e.payer}</span></td><td><span className="pill">{e.category}</span></td><td>{e.split_type}</td><td>{e.participants}</td><td><strong>{money(e.amount)}</strong></td></tr>)}{!expenses.length&&<tr><td colSpan="6" className="empty">No expenses match your search.</td></tr>}</tbody></table></div></div>}

function Balances({balances,money}){return <div className="panel table-panel"><header><div><h2>Balances</h2><p>Net amount each member should receive or pay.</p></div><span className="soft-chip">Auto calculated</span></header><div className="balance-cards">{balances.map(b=><div className="member-balance" key={b.user_id}><div className="person"><span className="avatar">{initials(b.name)}</span><span><b>{b.name}</b><small>Paid {money(b.paid)} · Share {money(b.owed)}</small></span></div><strong className={b.balance>=0?'positive':'negative'}>{b.balance>=0?'gets ':'owes '}{money(Math.abs(b.balance))}</strong></div>)}</div></div>}

function Members({groupId,members,onAdd,onDone}){const [removing,setRemoving]=useState(null),[error,setError]=useState('');const remove=async member=>{if(!window.confirm(`Remove ${member.name} from this group? Their account and existing history will be kept.`))return;setRemoving(member.user_id);setError('');try{await api.removeMember(groupId,member.user_id);onDone()}catch(e){setError(e.message)}finally{setRemoving(null)}};return <div className="panel table-panel"><header><div><h2>Group members</h2><p>People included in expense splitting.</p></div><button className="primary small" onClick={onAdd}><UserPlus size={16}/>Add member</button></header>{error&&<div className="form-error members-error" role="alert">{error}</div>}<div className="member-grid">{members.map(m=>{const protectedRole=['owner','admin'].includes(String(m.role).toLowerCase());return <div className="member-card" key={m.user_id}><span className="avatar large">{initials(m.name)}</span><div><h3>{m.name}</h3><p>{m.email}</p><span className="role">{m.role}</span></div><button type="button" className="icon-square remove-member" title={protectedRole?'Group owners and admins cannot be removed':'Remove from group'} aria-label={`Remove ${m.name} from group`} disabled={protectedRole||removing===m.user_id} onClick={()=>remove(m)}>{removing===m.user_id?'…':<Trash2 size={16}/>}</button></div>})}</div></div>}

function suggestedPayments(balances){const debtors=balances.filter(x=>Number(x.balance)<-0.005).map(x=>({...x,remaining:Math.round(Math.abs(Number(x.balance))*100)}));const creditors=balances.filter(x=>Number(x.balance)>0.005).map(x=>({...x,remaining:Math.round(Number(x.balance)*100)}));const payments=[];let debtorIndex=0,creditorIndex=0;while(debtorIndex<debtors.length&&creditorIndex<creditors.length){const debtor=debtors[debtorIndex],creditor=creditors[creditorIndex],cents=Math.min(debtor.remaining,creditor.remaining);if(cents>0)payments.push({from_user_id:debtor.user_id,from_name:debtor.name,to_user_id:creditor.user_id,to_name:creditor.name,amount:cents/100});debtor.remaining-=cents;creditor.remaining-=cents;if(debtor.remaining===0)debtorIndex++;if(creditor.remaining===0)creditorIndex++}return payments}

function Settlements({groupId,settlements,balances,money,onAdd,onDone}){const suggestions=suggestedPayments(balances),[saving,setSaving]=useState(false),[error,setError]=useState('');const record=async payment=>{if(!window.confirm(`Record ${money(payment.amount)} paid from ${payment.from_name} to ${payment.to_name}?`))return;setSaving(true);setError('');try{await api.settle(groupId,{from_user_id:payment.from_user_id,to_user_id:payment.to_user_id,amount:payment.amount});onDone()}catch(e){setError(e.message)}finally{setSaving(false)}};return <div className="stack"><section className="panel table-panel"><header><div><h2>Suggested payments</h2><p>Who should pay whom to settle current balances.</p></div><span className="soft-chip">{suggestions.length} payments</span></header><p className="payment-note">Transfer outside the app first, then mark the payment as paid here.</p>{suggestions.length?<div className="suggestion-list">{suggestions.map(payment=><div className="suggestion-row" key={`${payment.from_user_id}-${payment.to_user_id}`}><div className="suggestion-route"><div className="person"><span className="avatar small">{initials(payment.from_name)}</span><span><b>{payment.from_name}</b><small>pays</small></span></div><ArrowRight size={17}/><div className="person"><span className="avatar small">{initials(payment.to_name)}</span><span><b>{payment.to_name}</b><small>receives</small></span></div></div><strong>{money(payment.amount)}</strong><button className="primary small" disabled={saving} onClick={()=>record(payment)}>Mark paid</button></div>)}</div>:<div className="empty large">Everyone is settled up.</div>}{error&&<div className="form-error settlement-error">{error}</div>}</section><section className="panel table-panel"><header><div><h2>Payment history</h2><p>Recorded payments between group members.</p></div><button className="primary small" onClick={onAdd}><Plus size={16}/>Record payment</button></header>{settlements.length?<div className="settlement-list">{settlements.map(s=><div key={s.settlement_id}><span className="settle-icon"><ArrowRight size={18}/></span><span><b>{s.from_name} → {s.to_name}</b><small>{new Date(s.settled_at).toLocaleString('en-IN')}</small></span><strong>{money(s.amount)}</strong></div>)}</div>:<div className="empty large">No settlements recorded yet.</div>}</section></div>}

function Reports({categoryData,spent,budget,expenses,money}){return <div className="grid-two"><section className="panel"><header><div><h2>Category report</h2><p>Distribution of total spending</p></div></header><div className="report-chart"><ResponsiveContainer width="100%" height={290}><PieChart><Pie data={categoryData} dataKey="value" nameKey="name" innerRadius={70} outerRadius={105} paddingAngle={3}>{categoryData.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip formatter={v=>money(v)}/></PieChart></ResponsiveContainer></div><div className="legend">{categoryData.map((x,i)=><span key={x.name}><i style={{background:colors[i%colors.length]}}/>{x.name}<b>{money(x.value)}</b></span>)}</div></section><section className="panel"><header><div><h2>Project metrics</h2><p>Useful numbers for your DBSE demo</p></div></header><div className="metric-stack"><Metric label="Budget utilization" value={`${budget?Math.round(spent/budget*100):0}%`}/><Metric label="Total expenses" value={expenses.length}/><Metric label="Average expense" value={money(expenses.length?spent/expenses.length:0)}/><Metric label="Largest expense" value={money(Math.max(0,...expenses.map(x=>Number(x.amount))))}/></div></section></div>}
function Metric({label,value}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}

function Modal({title,children,onClose,description='Update your shared finance workspace.'}){return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={e=>e.stopPropagation()}><header><div><h2>{title}</h2><p>{description}</p></div><button className="icon-square" onClick={onClose}><X size={18}/></button></header>{children}</div></div>}

function ExpenseModal({groupId,members,onClose,onDone}){const [form,setForm]=useState({description:'',amount:'',payer_id:members[0]?.user_id||'',category:'Food',split_type:'equal'}),[saving,setSaving]=useState(false),[err,setErr]=useState('');const submit=async e=>{e.preventDefault();setSaving(true);setErr('');try{const splits=members.map(m=>({user_id:m.user_id,share:form.split_type==='percentage'?(100/members.length).toFixed(2):form.split_type==='exact'?'':0}));if(form.split_type==='exact')splits.forEach((s,i)=>s.share=document.getElementById(`share-${i}`)?.value||0);await api.addExpense(groupId,{...form,amount:Number(form.amount),payer_id:Number(form.payer_id),splits});onDone()}catch(e){setErr(e.message)}finally{setSaving(false)}};return <Modal title="Add expense" onClose={onClose}><form onSubmit={submit} className="form"><label>Description<input required value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="e.g. Team dinner"/></label><div className="form-row"><label>Amount<input required type="number" min="1" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder="₹ 0"/></label><label>Payer<select value={form.payer_id} onChange={e=>setForm({...form,payer_id:e.target.value})}>{members.map(m=><option key={m.user_id} value={m.user_id}>{m.name}</option>)}</select></label></div><div className="form-row"><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{['Food','Travel','Study','Shopping','Bills','Other'].map(x=><option key={x}>{x}</option>)}</select></label><label>Split method<select value={form.split_type} onChange={e=>setForm({...form,split_type:e.target.value})}><option value="equal">Equal</option><option value="percentage">Percentage</option><option value="exact">Exact share</option></select></label></div>{form.split_type==='exact'&&<div className="split-inputs">{members.map((m,i)=><label key={m.user_id}>{m.name}<input id={`share-${i}`} type="number" min="0" step="0.01" placeholder="0"/></label>)}</div>} {err&&<div className="form-error">{err}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={saving}>{saving?'Saving…':'Save expense'}</button></div></form></Modal>}

function MemberModal({groupId,users,existingMembers,onClose,onDone}){const [mode,setMode]=useState('existing'),[user_id,setUser]=useState(''),[name,setName]=useState(''),[email,setEmail]=useState(''),[err,setErr]=useState(''),[saving,setSaving]=useState(false);const memberIds=new Set(existingMembers.map(m=>m.user_id));const availableUsers=users.filter(u=>!memberIds.has(u.user_id));useEffect(()=>{if(!user_id&&availableUsers.length)setUser(availableUsers[0].user_id)},[availableUsers,user_id]);const submit=async e=>{e.preventDefault();setErr('');setSaving(true);try{const body=mode==='existing'?{user_id:Number(user_id)}:{name,email};await api.addMember(groupId,body);onDone()}catch(e){setErr(e.message)}finally{setSaving(false)}};return <Modal title="Add member" onClose={onClose}><form className="form" onSubmit={submit}><div className="member-mode" role="group" aria-label="Member type"><button type="button" className={mode==='existing'?'active':''} aria-pressed={mode==='existing'} onClick={()=>{setMode('existing');setErr('')}}>Existing user</button><button type="button" className={mode==='new'?'active':''} aria-pressed={mode==='new'} onClick={()=>{setMode('new');setErr('')}}>New person</button></div>{mode==='existing'?availableUsers.length?<label>Select person<select required value={user_id} onChange={e=>setUser(e.target.value)}>{availableUsers.map(u=><option key={u.user_id} value={u.user_id}>{u.name}{u.email?` — ${u.email}`:''}</option>)}</select></label>:<div className="empty">All existing users are already in this group.</div>:<><label>Full name<input required maxLength="80" value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Surya Prakash"/></label><label>Email address<input required type="email" maxLength="120" value={email} onChange={e=>setEmail(e.target.value)} placeholder="surya@example.com"/></label></>}{err&&<div className="form-error">{err}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={saving||(mode==='existing'&&!availableUsers.length)}>{saving?'Adding…':'Add member'}</button></div></form></Modal>}

function SettlementModal({groupId,balances,onClose,onDone}){const positive=balances.filter(b=>b.balance<0),receivers=balances.filter(b=>b.balance>0);const [from,setFrom]=useState(positive[0]?.user_id||''),[to,setTo]=useState(receivers[0]?.user_id||''),[amount,setAmount]=useState('');return <Modal title="Record settlement" onClose={onClose}><form className="form" onSubmit={async e=>{e.preventDefault();try{await api.settle(groupId,{from_user_id:Number(from),to_user_id:Number(to),amount:Number(amount)});onDone()}catch(e){alert(e.message)}}}><div className="form-row"><label>From<select value={from} onChange={e=>setFrom(e.target.value)}>{positive.map(x=><option key={x.user_id} value={x.user_id}>{x.name}</option>)}</select></label><label>To<select value={to} onChange={e=>setTo(e.target.value)}>{receivers.map(x=><option key={x.user_id} value={x.user_id}>{x.name}</option>)}</select></label></div><label>Amount<input required type="number" min="1" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="₹ 0"/></label><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary">Record payment</button></div></form></Modal>}

function GroupModal({groups,groupId,setGroupId,onClose,onDone}){const [creating,setCreating]=useState(false),[name,setName]=useState(''),[budget,setBudget]=useState('');return <Modal title="Switch group" onClose={onClose}><div className="group-list">{groups.map(g=><button className={g.group_id===groupId?'selected':''} key={g.group_id} onClick={()=>{setGroupId(g.group_id);onClose()}}><span className="group-icon">{g.name.slice(0,1)}</span><span><b>{g.name}</b><small>{g.members} members · {money(g.spent)} spent</small></span><CheckCircle2 size={17}/></button>)}</div>{!creating?<button className="outline-wide" onClick={()=>setCreating(true)}><Plus size={16}/>Create another group</button>:<form className="form compact" onSubmit={async e=>{e.preventDefault();const g=await api.createGroup({name,budget:Number(budget)});const all=await api.groups();setGroupId(g.group_id);onDone(all)}}><label>Group name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Weekend Trip"/></label><label>Budget<input required type="number" min="1" value={budget} onChange={e=>setBudget(e.target.value)} placeholder="25000"/></label><button className="primary">Create group</button></form>}</Modal>}

export default App
